### PR TITLE
update expected java results

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by johnmay** [comment]
I see this is the same as the Python but did you look why the RMSD increases? I know there order is different but is it just selecting the first match and then improving it - I would have thought it would explore all possible matches and choose the min therefore the result would be the same...

**Comment by greglandrum** [comment]
That code doesn't explore all possible isomorphisms, it just takes the first one provided and uses it.

**Comment by greglandrum** [comment]
The alignment code does not, by default, take all possible isomorphisms into account and select the best. It uses the mapping provided by the user or, if there isn't one, use the first match it finds
There *is* code to return the best alignment, but this isn't it.

**Comment by johnmay** [comment]
Okay no problem then.

**Pull request merged**
